service: nestjs-serverless-dynamo
plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dynamodb
functions:
  app:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'


  myFunction1:
    handler: handler.myFunction1
    runtime: nodejs18.x
    environment:
      TABLE_NAME: "Users"

  useTable:
    handler: handler.useTable
    environment:
      DYNAMODB_TABLE: "Users"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    tableName: "Users"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::remix-bucket/*"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource: '*'

  apiGateway:
    shouldStartNameWithService: true

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:DescribeTable'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'

          Resource: arn:aws:dynamodb:us-east-1:*:table/Users


custom:

  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: aws-sdk
    target: node14
    define: 'require.resolve: undefined'
    platform: node
    concurrency: 10

  dynamodb:
    start:
      port: 6000
      inMemory: true
      migrate: true
    stages: dev




