export const PASSWORD_INCORRECT = 'Password too weak'
export const PASSWORDS_DO_NOT_MATCH= 'Password and confirmPassword do not match'
export const EMAIL_IS_ALREADY_IN_USE = 'Email is already in use'
export const USER_REGISTERED_SUCCESSFULLY='User registered successfully'
export const RETRIEVED_SUCCESSFULLY='Retrieved successfully!'
export const INCORRECT_CREDENTIALS='Incorrect credentials!'
